version: 0.2

phases:
  install:
    commands:
      - curl -sSL https://dl.google.com/go/go1.17.3.linux-amd64.tar.gz | tar -C /usr/local -xz
      - export PATH=$PATH:/usr/local/go/bin
      - go version
  build:
    commands:
      - GOOS=linux GOARCH=amd64 go build -o myapp .
  post_build:
    commands:
      - ls -al
artifacts:
  files:
    - myapp
    - Procfile
